//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First.WindowClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PumpEntities : DbContext
    {
        public PumpEntities()
            : base("name=PumpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Pump_Tb> Pump_Tb { get; set; }
        public DbSet<PendingQueue> PendingQueues { get; set; }
    
        public virtual int DequePending(ObjectParameter nextId)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DequePending", nextId);
        }
    
        public virtual int EnquePending(Nullable<System.DateTime> dueTime, Nullable<System.Guid> brokerMessageId)
        {
            var dueTimeParameter = dueTime.HasValue ?
                new ObjectParameter("dueTime", dueTime) :
                new ObjectParameter("dueTime", typeof(System.DateTime));
    
            var brokerMessageIdParameter = brokerMessageId.HasValue ?
                new ObjectParameter("brokerMessageId", brokerMessageId) :
                new ObjectParameter("brokerMessageId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnquePending", dueTimeParameter, brokerMessageIdParameter);
        }
    }
}
